---

- include_tasks: app_base.yml

- include_tasks: app_dev_libraries.yml

- include_tasks: app_gum.yml

- include_tasks: app_btop.yml

- include_tasks: app_geekbench.yml

- include_tasks: app_fastfetch.yml

- include_tasks: app_gh.yml

- include_tasks: app_lazydocker.yml

- include_tasks: app_lazygit.yml

- include_tasks: app_shell_utils.yml

- include_tasks: app_mise.yml
