---

- block:

    - name: Add github cli repository using key from URL
      ansible.builtin.deb822_repository:
        name: github-cli
        types: deb
        uris: https://cli.github.com/packages
        suites: stable
        components: main
        architectures: amd64,arm64,armhf
        signed_by: https://cli.github.com/packages/githubcli-archive-keyring.gpg

    - name: install gh
      ansible.builtin.package:
        name: "{{ workstation_gh_package }}"
        state: latest
        update_cache: yes

  when: want_workstation_gh
