---

- block:

    - name: check current install
      ansible.builtin.stat:
        path: "{{ workstation_geekbench_bin }}"
      register: t_workstation_geekbench_bin

    - block:

        - name: download geekbench
          ansible.builtin.get_url:
            url: "{{ workstation_geekbench_url }}"
            dest: "/tmp/{{ workstation_geekbench_archive_name }}.tar.gz"

        - name: extract archive
          ansible.builtin.unarchive:
            src: "/tmp/{{ workstation_geekbench_archive_name }}.tar.gz"
            dest: "{{ workstation_geekbench_local_dir }}"
            owner: root
            group: root
            remote_src: yes

        - name: cleanup
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "/tmp/{{ workstation_geekbench_archive_name }}.tar.gz"

      when: not t_workstation_geekbench_bin.stat.exists

    - name: create bin shortcut
      ansible.builtin.file:
        src: "{{ workstation_geekbench_bin }}"
        dest: "{{ workstation_geekbench_local_bin_dir }}/{{ workstation_geekbench_bin_name }}"
        state: link
        force: yes
        follow: no

  when: want_workstation_geekbench
