---

- block:

    - name: download GitHub CLI keyring
      ansible.builtin.get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
        mode: '0644'
        owner: root
        group: root

    - name: add GitHub CLI repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        state: present
        filename: github-cli

    - name: install gh
      ansible.builtin.package:
        name: "{{ workstation_gh_package }}"
        state: present
        update_cache: yes
      become: yes

  when: want_workstation_gh
